steps:
# Slack notification
- name: 'gcr.io/$_CONTAINER_PROJECT/slackbot'
  id: Slack notification
  args: [ '--build', '$BUILD_ID',
          '--webhook', '$_SLACK_WEBHOOK' ]
  waitFor: ['-']

# Create file for version endpoint
- name: 'gcr.io/cloud-builders/git'
  id: Create_version_file
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    echo '{' > ./app/services/default/version.txt
    echo '  "REPO_NAME": "'${REPO_NAME}'",' >> ./app/services/default/version.txt
    echo '  "BRANCH_NAME": "'${BRANCH_NAME}'",' >> ./app/services/default/version.txt
    echo '  "TAG_NAME": "'${TAG_NAME}'",' >> ./app/services/default/version.txt
    echo '  "REVISION_ID": "'${REVISION_ID}'",' >> ./app/services/default/version.txt
    echo '  "COMMIT_SHA": "'${COMMIT_SHA}'",' >> ./app/services/default/version.txt
    echo '  "SHORT_SHA": "'${SHORT_SHA}'"' >> ./app/services/default/version.txt
    echo '}' >> ./app/services/default/version.txt
    cat ./app/services/default/version.txt
  waitFor: ['-']
