steps:
# Slack notification
- name: 'gcr.io/$_CONTAINER_PROJECT/slackbot'
  id: Slack notification
  args: [ '--build', '$BUILD_ID',
          '--webhook', '$_SLACK_WEBHOOK' ]
  waitFor: ['-']

# Create file for version endpoint
- name: 'gcr.io/cloud-builders/git'
  id: Create_version_file
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
   echo 'HELLO WORLD'
  waitFor: ['-']
